projects:
  drinkers:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: 27vityf625g4vhhlvsxtuebkxu
      endpoints:
        prod: >-
          https://62lkf76wyreojfdgph7kfkoz6q.appsync-api.ap-northeast-1.amazonaws.com/graphql
